{
 "title": "Differential Protection Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jitter Buffer Depth",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sapCemStatsEgressJtrBfrDepth{svcId=\"37941\", instance=\"172.16.8.53\"} * (sapCemPayloadSize{svcId=\"37941\", instance=\"172.16.8.53\"} * 0.125)",
     "legendFormat": "7705 SAR-8 53"
    },
    {
     "expr": "sapCemStatsEgressJtrBfrDepth{svcId=\"37941\", instance=\"172.16.8.63\"} * (sapCemPayloadSize{svcId=\"37941\", instance=\"172.16.8.63\"} * 0.125)",
     "legendFormat": "7705 SAR-8 63"
    }
   ]
  },
  {
   "title": "Two-Way Delay",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tmnxDot1agCfmMepDelayTestDelay{dot1agCfmMaIndex=\"106\", instance=\"172.16.8.63\"}",
     "legendFormat": "Path A"
    },
    {
     "expr": "tmnxDot1agCfmMepDelayTestDelay{dot1agCfmMaIndex=\"107\", instance=\"172.16.8.63\"}",
     "legendFormat": "Path B"
    },
    {
     "expr": "tmnxDot1agCfmMepDelayTestDelay{dot1agCfmMaIndex=\"108\", instance=\"172.16.8.63\"}",
     "legendFormat": "Path C"
    },
    {
     "expr": "tmnxDot1agCfmMepDelayTestDelay{dot1agCfmMaIndex=\"109\", instance=\"172.16.8.63\"}",
     "legendFormat": "Path D"
    }
   ]
  },
  {
   "title": "Underruns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sapCemStatsEgressJtrBfrUnderruns{instance=\"172.16.8.53\", svcId=\"37941\"}",
     "legendFormat": "SAR-8 53"
    },
    {
     "expr": "sapCemStatsEgressJtrBfrUnderruns{instance=\"172.16.8.63\", svcId=\"37941\"}",
     "legendFormat": "SAR-8 63"
    }
   ]
  },
  {
   "title": "Config parameters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sapCemBitrate{svcId=\"37941\", instance=\"172.16.8.53\"} * 64",
     "legendFormat": "SAP Bit-Rate"
    },
    {
     "expr": "sapCemPayloadSize{svcId=\"37941\", instance=\"172.16.8.53\"}",
     "legendFormat": "Payload Size"
    },
    {
     "expr": "sapCemJitterBuffer{svcId=\"37941\", instance=\"172.16.8.53\"}",
     "legendFormat": "Jitter Buffer"
    }
   ]
  },
  {
   "title": "Overruns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sapCemStatsEgressJtrBfrOverruns{instance=\"172.16.8.53\", svcId=\"37941\"}",
     "legendFormat": "SAR-8 53"
    },
    {
     "expr": "sapCemStatsEgressJtrBfrOverruns{instance=\"172.16.8.63\", svcId=\"37941\"}",
     "legendFormat": "SAR-8 63"
    }
   ]
  }
 ]
}